<?php
require __DIR__.'/auth.php';require_auth();$db=app_db();
$cols=array_column($db->query("PRAGMA table_info(users)")->fetchAll(PDO::FETCH_ASSOC),'name');
if(!in_array('role',$cols,true))$db->exec("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user'");
if(!in_array('email',$cols,true))$db->exec("ALTER TABLE users ADD COLUMN email TEXT NOT NULL DEFAULT ''");
$db->exec("UPDATE users SET role='admin' WHERE username='admin'");
$u=$db->prepare("SELECT role FROM users WHERE id=?");$u->execute([$_SESSION['user_id']]);if($u->fetchColumn()!=='admin'){http_response_code(403);exit('Нямате достъп до администрацията.');}
$db->exec("CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL)");
$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!hash_equals(csrf_token(),(string)($_POST['csrf']??'')))throw new RuntimeException('Невалидна заявка.');
  $action=$_POST['action']??'';
  if($action==='add_user'){
   $name=trim((string)($_POST['username']??''));$email=trim((string)($_POST['email']??''));$pass=(string)($_POST['password']??'');$role=(string)($_POST['role']??'user');
   if(!preg_match('/^[A-Za-z0-9._-]{3,60}$/',$name)||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190||strlen($pass)<8||!in_array($role,['admin','sales','inspections','warehouse','technician','records','supervisor'],true))throw new RuntimeException('Провери потребителя, паролата и ролята.');
   $s=$db->prepare("INSERT INTO users(username,email,password_hash,role,created_at) VALUES(?,?,?,?,datetime('now'))");$s->execute([$name,$email,password_hash($pass,PASSWORD_DEFAULT),$role]);$msg='Акаунтът е добавен.';
  }elseif($action==='edit_user'){
   $id=(int)($_POST['user_id']??0);$name=trim((string)($_POST['username']??''));$email=trim((string)($_POST['email']??''));$pass=(string)($_POST['password']??'');$role=(string)($_POST['role']??'user');
   if($id<1||!preg_match('/^[A-Za-z0-9._-]{3,60}$/',$name)||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190||($pass!==''&&strlen($pass)<8)||!in_array($role,['admin','sales','inspections','warehouse','technician','records','supervisor'],true))throw new RuntimeException('Провери данните за акаунта.');
   if($id===(int)$_SESSION['user_id']&&$role!=='admin')throw new RuntimeException('Не можеш да премахнеш собствената си администраторска роля.');
   if($pass!==''){$s=$db->prepare("UPDATE users SET username=?,email=?,role=?,password_hash=? WHERE id=?");$s->execute([$name,$email,$role,password_hash($pass,PASSWORD_DEFAULT),$id]);}
   else{$s=$db->prepare("UPDATE users SET username=?,email=?,role=? WHERE id=?");$s->execute([$name,$email,$role,$id]);}
   $msg='Акаунтът е променен.';
  }elseif($action==='delete_user'){
   $id=(int)($_POST['user_id']??0);if($id<1)throw new RuntimeException('Невалиден акаунт.');
   if($id===(int)$_SESSION['user_id'])throw new RuntimeException('Не можеш да изтриеш собствения си активен акаунт.');
   $s=$db->prepare("DELETE FROM users WHERE id=?");$s->execute([$id]);$msg='Акаунтът е изтрит.';
  }
 }catch(Throwable $e){$err=$e instanceof PDOException?'Потребителят вече съществува.':$e->getMessage();}
}
$settings=$db->query("SELECT key,value FROM app_settings")->fetchAll(PDO::FETCH_KEY_PAIR);$users=$db->query("SELECT id,username,email,role,created_at FROM users ORDER BY username")->fetchAll();
$storageOk=!empty($settings['owncloud_url'])&&!empty($settings['owncloud_user'])&&!empty($settings['owncloud_password']);
?><!doctype html><html lang="bg"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Администрация · INFO</title>
<style>:root{font-family:Inter,Segoe UI,Arial,sans-serif;background:#eff4f6;color:#173447}*{box-sizing:border-box}body{margin:0}.top{background:#183346;color:#fff;padding:16px max(24px,calc((100vw - 1180px)/2));display:flex;justify-content:space-between}.top a{color:#fff}.wrap{max-width:1180px;margin:auto;padding:34px 24px}h1{margin:0 0 6px}.sub{color:#607987;margin:0 0 24px}.status{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:22px}.pill{padding:7px 10px;border-radius:8px;background:#e3edf2;font-size:13px;font-weight:700}.ok{background:#e2f3e9;color:#26734f}.bad{background:#fbe7e4;color:#9b382d}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{background:#fff;border:1px solid #d9e4e9;border-radius:13px;padding:22px}.card h2{margin:0 0 5px;font-size:19px}.card p{color:#607987;font-size:14px}.card a.button,button{display:inline-block;background:#e9aa4b;color:#173447;border:0;border-radius:8px;padding:10px 14px;font-weight:750;text-decoration:none;cursor:pointer}label{display:block;font-size:13px;font-weight:650;margin:11px 0}input,select{width:100%;padding:10px;border:1px solid #c8d7de;border-radius:7px;margin-top:5px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:8px;border-bottom:1px solid #e4ecef}.msg{padding:10px;border-radius:8px;margin-bottom:15px;background:#e2f3e9}.err{background:#fbe7e4}.wide{grid-column:1/-1}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}.notify-tabs{display:flex;gap:6px;margin:14px 0;border-bottom:1px solid #d9e4e9}.notify-tab{background:transparent;border-radius:0;padding:9px 14px;border-bottom:3px solid transparent}.notify-tab.active{background:#eef4f7;border-bottom-color:#e9aa4b}.notify-panel[hidden]{display:none}.deleteBtn{background:#fbe7e4;color:#9b382d;margin-left:5px}.modalback{position:fixed;inset:0;background:#17344788;display:grid;place-items:center;z-index:10;padding:20px}.modalback[hidden]{display:none}.modal{background:#fff;border-radius:13px;padding:24px;width:min(480px,100%);box-shadow:0 20px 60px #0003}.modal h2{margin-top:0}.modalactions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}</style><link rel="stylesheet" href="/assets/tim-theme.css?v=20261003"></head><body>
<header class="top"><b>INFO · Администрация</b><a href="/">← Начало</a></header><main class="wrap"><h1>Системни настройки</h1><p class="sub">Потребители, роли, ownCloud и системни известия.</p>
<?php if($msg):?><div class="msg"><?=htmlspecialchars($msg)?></div><?php endif;if($err):?><div class="msg err"><?=htmlspecialchars($err)?></div><?php endif;?>
<div class="status"><span class="pill <?=!empty($settings['smtp_host'])?'ok':'bad'?>">SMTP <?=!empty($settings['smtp_host'])?'✓':'—'?></span><span class="pill <?=!empty($settings['telegram_chat_id'])?'ok':'bad'?>">Telegram <?=!empty($settings['telegram_chat_id'])?'✓':'—'?></span><span class="pill <?=$storageOk?'ok':'bad'?>">ownCloud <?=$storageOk?'✓ Конфигуриран':'Не е конфигуриран'?></span><span class="pill">Потребители <?=count($users)?></span></div>
<div class="grid">
<section class="card"><h2>Съхранение · ownCloud</h2><form id="oc"><label>ownCloud URL<input id="owncloud_url" placeholder="https://cloud.example.com"></label><label>Потребител<input id="owncloud_user"></label><label>Парола<input id="owncloud_password" type="password" autocomplete="new-password" placeholder="Въведи за промяна"></label><label>Основна папка<input id="owncloud_root" placeholder="INFO"></label><p id="ocSecret"></p><button>Запази ownCloud</button> <button type="button" id="testOc">Тествай връзката</button><p id="ocState"></p></form></section>
<section class="card"><h2>Известия</h2><div class="notify-tabs"><button type="button" class="notify-tab active" data-notify-tab="smtp">SMTP</button><button type="button" class="notify-tab" data-notify-tab="telegram">Telegram</button></div><form id="channels"><div id="notify-smtp" class="notify-panel"><label>SMTP сървър<input id="smtp_host"></label><label>Порт<input id="smtp_port" type="number"></label><label>Защита<select id="smtp_security"><option value="tls">STARTTLS</option><option value="ssl">SSL/TLS</option><option value="none">Без</option></select></label><label>Потребител<input id="smtp_user"></label><label>SMTP парола<input id="smtp_password" type="password" autocomplete="new-password"></label><label>Имейл подател<input id="smtp_from" type="email"></label><label>Име на подателя<input id="smtp_from_name"></label><label>Получател<input id="notification_email" type="email"></label></div><div id="notify-telegram" class="notify-panel" hidden><label>Telegram токен<input id="telegram_token" type="password" autocomplete="new-password"></label><label>Telegram Chat ID<input id="telegram_chat_id"></label></div><p id="notifySecret"></p><button>Запази известията</button><p id="notifyState"></p></form></section>
<section class="card"><h2>Добавяне на акаунт</h2><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="add_user"><label>Потребител<input name="username" required></label><label>Имейл<input name="email" type="email" required maxlength="190" placeholder="name@example.com"></label><label>Парола<input name="password" type="password" minlength="8" required></label><label>Роля<select name="role"><option value="sales">Търговец</option><option value="inspections">Огледи</option><option value="warehouse">Склад</option><option value="technician">Техник</option><option value="records">Деловодство</option><option value="supervisor">Супервайзор</option><option value="admin">Администратор</option></select></label><button>Добави акаунт</button></form></section>
<section class="card wide"><h2>Потребители</h2><table><thead><tr><th>Потребител</th><th>Имейл</th><th>Роля</th><th>Създаден</th><th>Действия</th></tr></thead><tbody><?php foreach($users as $x):?><tr><td><?=htmlspecialchars($x['username'])?></td><td><?=htmlspecialchars($x['email']??'')?></td><td><?=htmlspecialchars($x['role'])?></td><td><?=htmlspecialchars($x['created_at']??'')?></td><td><button type="button" class="editUser" data-user='<?=htmlspecialchars(json_encode(["id"=>$x["id"],"username"=>$x["username"],"email"=>$x["email"]??"","role"=>$x["role"]],JSON_UNESCAPED_UNICODE),ENT_QUOTES,"UTF-8")?>'>Редакция</button><?php if((int)$x['id']!==(int)$_SESSION['user_id']):?><form method="post" style="display:inline" onsubmit="return confirm('Сигурни ли сте, че искате да изтриете този акаунт?')"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?=htmlspecialchars($x['id'])?>"><button type="submit" class="deleteBtn">Изтриване</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></section>
<div id="editModal" class="modalback" hidden><div class="modal"><h2>Редакция на акаунт</h2><form method="post" id="editUserForm"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="edit_user"><input type="hidden" name="user_id" id="edit_user_id"><label>Потребител<input name="username" id="edit_username" required></label><label>Имейл<input name="email" id="edit_email" type="email" required></label><label>Нова парола<input name="password" type="password" minlength="8" placeholder="Остави празно без промяна"></label><label>Роля<select name="role" id="edit_role"><option value="sales">Търговец</option><option value="inspections">Огледи</option><option value="warehouse">Склад</option><option value="technician">Техник</option><option value="records">Деловодство</option><option value="supervisor">Супервайзор</option><option value="admin">Администратор</option></select></label><div class="modalactions"><button type="button" id="cancelEdit">Отказ</button><button type="submit">Запази промените</button></div></form></div></div>
</div></main><script>
async function api(p){let r=await fetch('/settings-api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Грешка');return d}
function fill(d){let x=d.settings||{};for(let k of ['owncloud_url','owncloud_user','owncloud_root','smtp_host','smtp_port','smtp_security','smtp_user','smtp_from','smtp_from_name','notification_email','telegram_chat_id']){let e=document.getElementById(k);if(e)e.value=x[k]||''}ocSecret.textContent=x.owncloud_password_configured?'ownCloud паролата е запазена.':'Няма запазена ownCloud парола.';notifySecret.textContent='SMTP: '+(x.smtp_password_configured?'паролата е запазена':'няма парола')+' · Telegram: '+(x.telegram_token_configured?'токенът е запазен':'няма токен')}
fetch('/settings-api.php',{cache:'no-store'}).then(r=>r.json()).then(fill);document.querySelectorAll('.editUser').forEach(b=>b.onclick=()=>{let u=JSON.parse(b.dataset.user);edit_user_id.value=u.id;edit_username.value=u.username;edit_email.value=u.email;edit_role.value=u.role;editModal.hidden=false});cancelEdit.onclick=()=>editModal.hidden=true;editModal.onclick=e=>{if(e.target===editModal)editModal.hidden=true};
document.querySelectorAll('.notify-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.notify-tab').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('notify-smtp').hidden=b.dataset.notifyTab!=='smtp';document.getElementById('notify-telegram').hidden=b.dataset.notifyTab!=='telegram'});
oc.onsubmit=async e=>{e.preventDefault();try{let settings={};for(let k of ['owncloud_url','owncloud_user','owncloud_password','owncloud_root'])settings[k]=document.getElementById(k).value;fill(await api({action:'owncloud',settings}));ocState.textContent='✓ Настройките са запазени.'}catch(x){ocState.textContent='✗ '+x.message}}
testOc.onclick=async()=>{ocState.textContent='Проверка…';try{let d=await api({action:'test_owncloud'});ocState.textContent='✓ '+d.message}catch(x){ocState.textContent='✗ '+x.message}}
channels.onsubmit=async e=>{e.preventDefault();try{let settings={};for(let k of ['smtp_host','smtp_port','smtp_security','smtp_user','smtp_password','smtp_from','smtp_from_name','notification_email','telegram_token','telegram_chat_id'])settings[k]=document.getElementById(k).value;fill(await api({action:'channels',settings}));notifyState.textContent='✓ Настройките са запазени.'}catch(x){notifyState.textContent='✗ '+x.message}}
</script></body></html>
